Id: Microsoft.dotnetRuntime
Version: 3.1.8.29220
Name: .NET Core Runtime
Publisher: Microsoft Corporation
License: Copyright (c) Microsoft Corporation. All rights reserved.
LicenseUrl: https://www.microsoft.com/en-us/legal/intellectualproperty/copyright/default
AppMoniker: dotNETruntime
Tags: .NET, .NET Core, dotnet, net, C#, csharp, F#, fsharp, VB, Visual Basic
Description: .NET Core Runtime is required to run an to run existing .NET Core application.
Homepage: https://dotnet.microsoft.com/download/dotnet-core/current/runtime
Installers:
- Arch: x64
  Url: https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-desktop-3.1.8-windows-x64-installer
  Sha256: 112DA330A41C6B53F4255D387B44F4D402133ED401BE8C8F5EEDA2617B76137A
  InstallerType: exe
  Scope: machine
  Switches:
    Silent: /quiet /norestart
    SilentWithProgress: /passive
    Custom: /install
