Id: PDFsam.PDFsam
Name: PDFsam Basic
Version: 4.1.4
Publisher: PDFsam
License: GNU Affero General Public License
LicenseUrl: https://www.gnu.org/licenses/agpl-3.0.html
AppMoniker: PDFsam
Description: PDFsam Basic or PDF Split and Merge is a free and open-source cross-platform desktop application to split, merge, extract pages, rotate and mix PDF documents.
Homepage: http://www.pdfsam.org/
Tags: PDF
InstallerType: MSI

# ======================= Installers  ==================  
 
Installers:  
  - Arch: x64
    Url: https://github.com/torakiki/pdfsam/releases/download/v4.1.4/pdfsam-4.1.4.msi
    Sha256: 8fb5f22885bafeded489a57e278f6cea77a96aa36529cc4f9b3da84479215852
