Id: Inkscape.Inkscape
Version: 1.0.1
Name: Inkscape
Publisher: The Inkscape Project
License: GPL 3.0 or later
LicenseUrl: https://inkscape.org/about/license/
AppMoniker: inkscape
Tags: "inkscape, editor, foss, cross-platform, svg, vector-graphics, icons, graphics, export, drawing, art"
Description: Inkscape is a free and open-source vector graphics editor used to create vector images, primarily in Scalable Vector Graphics (SVG) format.
Homepage: https://inkscape.org/
Installers:
  - Arch: x64
    Url: https://inkscape.org/gallery/item/21592/inkscape-1.0.1-x64.msi
    Sha256: 8bcca5b3bbdd466e2b95b3de99a291d7f2737a7c31f5f2004e16b4b9ebd79f5b
    InstallerType: msi
